export default [
	'The Legend of Zelda',
	'Super Mario Odyssey',
	'Halo: Combat Evolved',
	'Final Fantasy VII',
	'Minecraft',
	'Overwatch',
	'Red Dead Redemption 2',
	'Dark Souls',
	'The Witcher 3: Wild Hunt',
	'Grand Theft Auto V',
	'Super Smash Bros. Ultimate',
	'Portal 2',
	'Stardew Valley',
	'Celeste',
	'Bloodborne',
	'Breath of the Wild',
	'Skyrim',
	'Rocket League',
	'God of War',
	'Animal Crossing: New Horizons',
	'Splatoon 2',
	'Cuphead',
	'Assassin’s Creed Odyssey',
	'Resident Evil 4',
	'Tetris',
	'Uncharted 4: A Thief’s End',
	'Fortnite',
	'Firewatch',
	'Hollow Knight',
];
